#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ -z "${INSTALL_PACKAGES:-}" ] && [ -n "${AUTOMATED_CONVERSION_INSTALL_PKGS:-}" ]
then
    >&2 echo "Usage of AUTOMATED_CONVERSION_INSTALL_PKGS environment variable is deprecated.  INSTALL_PACKAGES should be used instead."
    echo "$AUTOMATED_CONVERSION_INSTALL_PKGS"
else
    exit 100
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
