#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

AUTOMATED_CONVERSION_PRESET="${AUTOMATED_CONVERSION_PRESET:-Very Fast 1080p30}"
AUTOMATED_CONVERSION_FORMAT="${AUTOMATED_CONVERSION_FORMAT:-mp4}"

FAILED_CONVERSIONS="/config/failed_conversions"
SUCCESSFUL_CONVERSIONS="/config/successful_conversions"

HANDBRAKE_CLI="$APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /usr/bin/HandBrakeCLI --preset-import-file /config/ghb/presets.json"

log() {
    echo "watchFolder: $*"
}

process_files() {
    for file in $1; do
        hash="$(stat -c '%n %s %Y' "$file" | md5sum | cut -d' ' -f1)"
        if grep -q -w "$hash" "$SUCCESSFUL_CONVERSIONS"; then
            log "Skipping file '$file' ($hash): already processed successfully."
            continue
        fi
        if grep -q -w "$hash" "$FAILED_CONVERSIONS"; then
            log "Skipping file '$file' ($hash): already processed with failure."
            continue
        fi

        log "Starting conversion of '$file' ($hash)..."
        basename="$(basename $file | sed 's/\.[^.]*$//')"
        $HANDBRAKE_CLI -i "$file" \
                       -o /output/"$basename"."$AUTOMATED_CONVERSION_FORMAT" \
                       --preset "$AUTOMATED_CONVERSION_PRESET"
        if [ $? -eq 0 ]; then
            log "Conversion ended successfully."
            echo "$file $hash" >> "$SUCCESSFUL_CONVERSIONS"
        else
            log "Conversion failed."
            echo "$file $hash" >> "$FAILED_CONVERSIONS"
        fi
    done
}

echo "Starting watchfolder service..."

[ -f "$FAILED_CONVERSIONS" ] || touch "$FAILED_CONVERSIONS"
[ -f "$SUCCESSFUL_CONVERSIONS" ] || touch "$SUCCESSFUL_CONVERSIONS"

DIRHASH=UNSET
while true; do
    CONTENT="$(find /watch -maxdepth 1 -type f -printf '%T@:%s:%p\n')"
    HASH="$(echo "$CONTENT" | md5sum | cut -d' ' -f1)"
    FILES="$(echo "$CONTENT" | cut -d':' -f3)"

    if [ "$DIRHASH" != "$HASH" ]; then
        if [ "$DIRHASH" != "UNSET" ]; then
            log "Watch folder: New file(s) detected!"
        fi
        log "Processing watch folder..."  
        process_files "$FILES"
        log "Watch folder processing terminated"
        DIRHASH="$HASH"
    fi

    sleep 5
done

# vim: set ft=sh :
