#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

AUTOMATED_CONVERSION_PRESET="${AUTOMATED_CONVERSION_PRESET:-Very Fast 1080p30}"
AUTOMATED_CONVERSION_FORMAT="${AUTOMATED_CONVERSION_FORMAT:-mp4}"

FAILED_CONVERSIONS="/config/failed_conversions"
SUCCESSFUL_CONVERSIONS="/config/successful_conversions"

HANDBRAKE_CLI="$APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /usr/bin/HandBrakeCLI --preset-import-file /config/ghb/presets.json"

log() {
    echo "watchFolder: $*"
}

watchdir_hash() {
    find /watch -follow -maxdepth 1 -type f -printf '%T@:%s:%p\n' | md5sum | cut -d' ' -f1
}

process_file() {
    file="$1"
    hash="$(stat -c '%n %s %Y' "$file" | md5sum | cut -d' ' -f1)"
    if grep -q -w "$hash" "$SUCCESSFUL_CONVERSIONS"; then
        log "Skipping file '$file' ($hash): already processed successfully."
        continue
    fi
    if grep -q -w "$hash" "$FAILED_CONVERSIONS"; then
        log "Skipping file '$file' ($hash): already processed with failure."
        continue
    fi

    log "Starting conversion of '$file' ($hash)..."
    basename="$(basename "$file" | sed 's/\.[^.]*$//')"
    $HANDBRAKE_CLI -i "$file" \
                   -o /output/"$basename.$AUTOMATED_CONVERSION_FORMAT" \
                   --preset "$AUTOMATED_CONVERSION_PRESET"
    if [ $? -eq 0 ]; then
        log "Conversion ended successfully."
        echo "$file $hash" >> "$SUCCESSFUL_CONVERSIONS"
        if [ "${AUTOMATED_CONVERSION_KEEP_SOURCE:-1}" -eq 0 ]; then
            rm "$file"
            log "Removed file '$file'."
        fi
    else
        log "Conversion failed."
        echo "$file $hash" >> "$FAILED_CONVERSIONS"
    fi
}

echo "Starting watchfolder service..."

[ -f "$FAILED_CONVERSIONS" ] || touch "$FAILED_CONVERSIONS"
[ -f "$SUCCESSFUL_CONVERSIONS" ] || touch "$SUCCESSFUL_CONVERSIONS"

DIRHASH=UNSET
while true; do
    PREHASH="$(watchdir_hash)"
    if [ "$DIRHASH" != "$PREHASH" ]; then
        if [ "$DIRHASH" != "UNSET" ]; then
            log "Watch folder: New file(s) detected!"
        fi
        log "Processing watch folder..."  
        find /watch -follow -maxdepth 1 -type f | while read FILE
        do
            process_file "$FILE"
        done
        log "Watch folder processing terminated"
        POSTHASH="$(watchdir_hash)"
        if [ "$DIRHASH" == "UNSET" ] || [ "$PREHASH" == "$POSTHASH" ]; then
            DIRHASH="$PREHASH"
        fi
    fi

    sleep 5
done

# vim: set ft=sh :
