#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

AUTOMATED_CONVERSION_PRESET="${AUTOMATED_CONVERSION_PRESET:-Very Fast 1080p30}"
AUTOMATED_CONVERSION_FORMAT="${AUTOMATED_CONVERSION_FORMAT:-mp4}"

FAILED_CONVERSIONS="/config/failed_conversions"
SUCCESSFUL_CONVERSIONS="/config/successful_conversions"

HANDBRAKE_CLI="$APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /usr/bin/HandBrakeCLI --preset-import-file /config/ghb/presets.json"

log() {
    echo "watchFolder: $*"
}

process_watch_folder() {
    while true; do
        file_processed=false

        for file in $(find /watch -type f); do
            hash="$(stat -c '%n %s %Y' "$file" | md5sum |  cut -d' ' -f1)"
            if grep -q -w "$hash" "$SUCCESSFUL_CONVERSIONS"; then
                log "Skipping file '$file' ($hash): already processed successfully."
                continue
            fi
            if grep -q -w "$hash" "$FAILED_CONVERSIONS"; then
                log "Skipping file '$file' ($hash): already processed with failure."
                continue
            fi

            log "Starting conversion of '$file' ($hash)..."
            basename="$(basename $file | sed 's/\.[^.]*$//')"
            $HANDBRAKE_CLI -i "$file" \
                           -o /output/"$basename"."$AUTOMATED_CONVERSION_FORMAT" \
                           --preset "$AUTOMATED_CONVERSION_PRESET"
            if [ $? -eq 0 ]; then
                log "Conversion ended successfully."
                echo "$file $hash" >> "$SUCCESSFUL_CONVERSIONS"
            else
                log "Conversion failed."
                echo "$file $hash" >> "$FAILED_CONVERSIONS"
            fi
            file_processed=true
        done

        $file_processed || break
        log "Re-processing watch folder for any missed files..."
    done
}

echo "Starting watchfolder service..."

[ -f "$FAILED_CONVERSIONS" ] || touch "$FAILED_CONVERSIONS"
[ -f "$SUCCESSFUL_CONVERSIONS" ] || touch "$SUCCESSFUL_CONVERSIONS"

process_watch_folder
while true; do
    /usr/bin/inotifywait -e close_write -e moved_to /watch 2> /dev/null
    if [ $? -eq  0 ]; then
        log "Watch folder: New file(s) detected!"
        log "Processing watch folder..."  
        process_watch_folder
        log "Watch folder processing terminated"
    fi
done

# vim: set ft=sh :
